#!/bin/bash

for k in `seq 2 10`
do
    for i in `seq 1 10`
    do 
        sbatch --job-name=case2383_750_batch_$i --output=./output/case2383_750_batch_$i.txt ./runscript.sh --file pglib_opf_case2383wp_k_nk.m --algo Lshaped --timeout 86400 --batchsize 750 --batchid $i --numbatches 10 --budget $k --parallel y --workers 16
    done
done

